#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in2,    light,          sensorReflection)
#pragma config(Sensor, in3,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  encoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  bump,           sensorTouch)
#pragma config(Sensor, dgtl6,  limit,          sensorTouch)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           lMotor,        tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Ben Godfrey    *
 * POE 8th Period *
 * Activity 3.1.5 *
 * 03/22/2017     */

typedef struct { // define object type "record" with 3 properties.
	string label;  // Label of the record
	int min;       // Minimum record value
	int max;       // Maximum record value
} record;

void resetRecord(record &inputRecord, int inputValue) { // clears records
	inputRecord.min = inputValue; // set min on record to default
	inputRecord.max = inputValue; // set max on record to default
}

void checkRecord(record &inputRecord, int inputValue) { //compares data to min/max
	if (inputValue > inputRecord.max) { // if input greater than max on record,
		inputRecord.max = inputValue;     // set max on record
	}

	if (inputValue < inputRecord.min) { // if input less than min on record,
		inputRecord.min = inputValue;     // set min on record
	}
}

void logRecord(record inputRecord) { // write record info to console on computer for monitoring
	writeDebugStreamLine("%s: %d-%d", inputRecord.label, inputRecord.min, inputRecord.max);
}

task main() {

	// declare records
	record potentialRecord;
	record sonarRecord;

	// set record labels
	potentialRecord.label = "Potentiometer";
	sonarRecord.label = "Sonar";

	// clear all records
	resetRecord(potentialRecord, SensorValue[potentiometer]);
	resetRecord(sonarRecord, SensorValue[sonar]);

	while (true) {
		// check all records against their sensors and make changes.
		checkRecord(potentialRecord, SensorValue[potentiometer]);
		checkRecord(sonarRecord, SensorValue[sonar]);

		// clear console before writing data
		clearDebugStream();

		// log/output record data to console for viewing
    logRecord(potentialRecord);
		logRecord(sonarRecord);

		// stop program if button pressed
		if (SensorValue[bump] == 1) {	break; }

	}

}
